# ~/InvisVM/context_menu_installer.py
"""
Context Menu Installer
Sets up right-click menu for Pop!_OS Nautilus file manager
"""

import os
import subprocess
import stat
from pathlib import Path

class ContextMenuInstaller:
    """
    Installs and manages right-click context menu
    """
    
    def __init__(self):
        """Initialize installer"""
        self.home = str(Path.home())
        self.scripts_dir = os.path.join(
            self.home,
            '.local/share/nautilus/scripts'
        )
        self.app_dir = os.path.join(self.home, 'InvisVM')
        self.script_name = 'Open-with-InvisVM'
        self.script_path = os.path.join(self.scripts_dir, self.script_name)
    
    def install(self):
        """
        Install context menu script
        
        Returns:
            Tuple (success: bool, message: str)
        """
        try:
            # Create scripts directory if needed
            os.makedirs(self.scripts_dir, exist_ok=True)
            
            # Create script content
            script_content = self._get_script_content()
            
            # Write script
            with open(self.script_path, 'w') as f:
                f.write(script_content)
            
            # Make executable
            os.chmod(self.script_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
            
            # Restart Nautilus to apply changes
            subprocess.run(['killall', 'nautilus'], capture_output=True)
            
            return True, f'Context menu installed successfully at {self.script_path}'
        
        except Exception as e:
            return False, f'Failed to install context menu: {str(e)}'
    
    def uninstall(self):
        """
        Uninstall context menu script
        
        Returns:
            Tuple (success: bool, message: str)
        """
        try:
            if os.path.exists(self.script_path):
                os.remove(self.script_path)
                
                # Restart Nautilus
                subprocess.run(['killall', 'nautilus'], capture_output=True)
                
                return True, 'Context menu uninstalled successfully'
            else:
                return False, 'Context menu script not found'
        
        except Exception as e:
            return False, f'Failed to uninstall context menu: {str(e)}'
    
    def is_installed(self):
        """Check if context menu is installed"""
        return os.path.exists(self.script_path)
    
    def _get_script_content(self):
        """
        Get content for context menu script
        
        Returns:
            Script content as string
        """
        return f"""#!/bin/bash
# InvisVM - Open with Firejail Sandbox
# Generated by InvisVM Context Menu Installer

# Get the selected file/folder
if [ -n "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" ]; then
    FILE_PATH="$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"
else
    FILE_PATH="$NAUTILUS_SCRIPT_CURRENT_URI"
fi

# Convert file:// URI to path if needed
FILE_PATH=$(echo "$FILE_PATH" | sed 's/file:\\/\\//\\//g')

# Launch InvisVM with policy selection dialog
python3 {self.app_dir}/main.py --select-policy --file "$FILE_PATH" &
"""